Confidence intervals from linear regression
genai-impact/ecologits pull request #104
Opened 2024-12-20 13:59 UTC by adrienbanse

Following https://github.com/genai-impact/ecologits/issues/95, for each value that is a result of a linear regression, we explicitely compute uncertainty and provide 95% confidence intervals with `y = f(x) +- 1.96 * std_dev`.

In the context of the computed impacts, the standard deviations for both the energy and the latency have been computed in https://github.com/genai-impact/methodology/blob/main/lab/lin_reg.ipynb. The impacts that depend on these values are therefore `ValueRange`, and not `float` or `int` such as before. 

This PR also adds somes tests for `ValueRange`, as `__mul__` and `__truediv__` operations were implented.

Remains to 
- [ ] Update the doc

2025-02-11 14:02 UTC, adrienbanse commented
(Optional) Following @NP4567-dev PR we can include an uncertainty mode in the config

2025-02-12 18:19 UTC, samuelrince requested changes

2025-02-12 18:19 UTC, samuelrince commented on docs/tutorial/impacts.md
> +This range of values corresponds a **high-confidence approximation interval**, within which we are confident enough that the true consumption lies (see the [methodology](../methodology/llm_inference.
I think we need to change this. It indeed corresponds to the "high-confidence approximation interval", but also to the estimation of model sizes for instance.

2025-02-12 18:19 UTC, samuelrince commented on docs/methodology/llm_inference.md
> +    The standard deviation $\delta$ of a linear regression measures "how close are the datapoints to the fitted line". A priori, the larger it is, the worse is the approximation. Consider a linear re
Maybe we should cite this as well for the 1.96 approximation (https://en.wikipedia.org/wiki/97.5th_percentile_point). Or any other better explanation / course.

2025-02-12 18:20 UTC, samuelrince commented
Also, let's not include the configuration part for now, I have reverted it temporarily!

2025-02-12 18:58 UTC, adrienbanse commented on docs/tutorial/impacts.md
> +This range of values corresponds a **high-confidence approximation interval**, within which we are confident enough that the true consumption lies (see the [methodology](../methodology/llm_inference.
Agreed, initially that's what I wanted to say, something like "We think it's in this interval for various reasons, including the approximation of the model size AND the error noise of the regression"

I'll rephrase and get back to you

2025-02-13 17:34 UTC, samuelrince approved these changes

2025-02-13 17:35 UTC, samuelrince commented
All good for me @adrienbanse !

2025-02-13 19:28 UTC, merged