Electricity mix flexibility
genai-impact/ecologits pull request #66
Opened 2024-07-25 14:56 UTC by adrienbanse

This PR implements

- [x] `ecologits/mix_repository.py` A mix repository from the ADEME database csv `ecologits/data/mixes.csv`
- [x] The possibility for the user to choose a mix when calling `llm_impacts`

Remaining things to implement : 
- [ ] Update the documentation
- [ ] Modify and implement tests

2024-08-23 09:09 UTC, samuelrince requested changes

2024-08-23 09:09 UTC, samuelrince commented on ecologits/impacts/llm.py
> +        if_electricity_mix_gwp: GWP impact factor of electricity consumption in kg of eq. CO2.
Change the units to be "[impact unit] / kWh". Also, I think it's better to stay coherent with the docs and use kgCO2eq and kgSbeq.

2024-08-23 09:09 UTC, samuelrince commented on ecologits/impacts/llm.py
> +        if_electricity_mix_gwp: GWP impact factor of electricity consumption in kg of eq. CO2.
Same comment for the units

2024-08-23 09:09 UTC, samuelrince commented on ecologits/mix_repository.py
> +class MixRepository:
For clarity, I would not use "Mix" but "ElectricityMix".

2024-08-23 09:09 UTC, samuelrince commented on ecologits/mix_repository.py
> +class Zones(Enum):
In my opinion, we should stick with country code instead of using and maintaining ourselves a list of country names and the match with [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3#User-assigned_code_elements) codes. Some libraries already exist and are dedicated to that, like pycountry (and others...)

Plus, I think that in the near future, end-users would rather have access to cloud regions instead of full country names (because they can always look for the country code).

2024-08-23 09:09 UTC, samuelrince commented on ecologits/tracers/utils.py
> +    if model is None:
Should be mix here instead of model

2024-08-27 08:14 UTC, adrienbanse commented on ecologits/electricity_mix_repository.py
> +reserved_codes = ["WOR", "EEE", "SCG"]
@samuelrince I based the tool on the alpha-3 codes, but there are some exceptions. Some codes are "reserved", but not officially country ISO codes. In the ADEME database, 3 of them are such codes, namely "WOR" (reserved for world), "EEE" (reserved for Europe) and "SCG" (reserved for Serbia and Montenegro). 

When I check with pycountry that the user uses a valid ISO code in `tracers/utils.py`, these codes are valid exceptions

2024-08-27 08:14 UTC, adrienbanse commented on ecologits/mix_repository.py
> +class Zones(Enum):
See https://github.com/genai-impact/ecologits/pull/66/commits/b09553b1a80dd8fd90e8e1ce3713c244cc62e317#r1732357942

2024-08-27 15:26 UTC, samuelrince commented
Thanks @adrienbanse, this looks good!

One remark about on the usage of `pycountry`. As I can see, we only use the library to check if a country code exists, right? But, we could also perform this check by just looking if the code exists in the electricity mix repository. Thus, the `pycountry` dependency is not really necessary, so I think we can remove it. Generally speaking, the less dependence we have the better, I would say! :)

If we want to support other country code formats, we can also pre-compute them in the file. I am working the `ecologits-data` repository mainly for the models, but we can integrate this file later with some logic.

We can work on the interface on how to change the country code in another PR about "configuration management", what do you think?

2024-08-28 07:15 UTC, adrienbanse commented
@samuelrince Agreed, I removed `pycountry` from the PR. 

Yes let's merge it as it is now, and let's open a PR in `ecologits-data` to handle alpha-2, alpha-3, official names etc. (and use `pycountry` there). I think we can even handle emoji flags 😄 

Yes this PR is only for the implementation of the flexibility, now I'll start to work on a general configuration in `Ecologits.init()` for choosing the mix, maybe a verbose parameter, ...

2024-08-28 12:33 UTC, merged